### ISSUE TITLE
IRC connection lost after receiving too large of a buffer.

### ISSUE THREAD

**Issue by meZee** [SFTtech/sftmumblebot#10]
After running the bot for a couple of hours it dies with

```
(0) irc: connection terminated with an error:
(0) irc: <class 'socket.error'>
(1) irc: Traceback (most recent call last):
(1) irc:   File "C:\Users\SwedFTP\Desktop\BTCBot\AbstractConnection.py", line 16
6, in run
(1) irc:     if not self._listen():
(1) irc:   File "C:\Users\SwedFTP\Desktop\BTCBot\IRCConnection.py", line 64, in
_listen
(1) irc:     self._readBuffer += self._socket.recv(1024)
(1) irc: error: [Errno 10053] An established connection was aborted by the softw
are in your host machine
(1) irc:
(2) irc: socket successfully closed
connection to irc lost. reconnect in 15 seconds.
```

I'm assuming it's because it's receiving larger than 1 kB of data, however I'm not sure of that, and I'm not quite sure how to reproduce this.

**Comment by TheJJ** [comment]
increased the read buffer to 4kb in 81ffee70947c9cba498b39e237852d12a6846510.
